spring.application.name=PaymentsLedger
spring.datasource.url=jdbc:mysql://localhost:3306/payments_ledger
spring.datasource.username=ledger_app
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true